config/routes.rb
Rails.application.routes.draw do
  resources :blogs, only:[:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  
  resources :contacts, only:[:new, :create] do
    collection do
      post :confirm
    end
  end
  
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]
  
  def index
    @blogs = Blog.all
  end
  
  def new
    if params[:back]
      @blog = Blog.new
    else
      @blog = Blog.new
    end
  end
  
  def create
    @blog = Blog.new(blogs_params)
    if @blog.save
      redirect_to blogs_path, notice: "作成しました！"
    else
      render 'new'
    end
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blogs_params)
      redirect_to blogs_path, notice: "編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "消去しました！"
  end
  
  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end

  private
    def blogs_params
      params.require(:blog).permit(:content)
    end
    
    def set_blog
      @blog = Blog.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>エラーがあります。</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :なにしている %>
  <%= f.text_field :content, class: 'form_control' %>
  <br>
  <%= f.submit '送信', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "一覧画面に戻る", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>これで大丈夫？</h3>
    <%= form_for(@blog) do |f| %>
      <%= f.hidden_field :content %>
      <p>本文:<%= @blog.content %></p>
      <%= f.submit "OK!!!",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる",  name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
  <p><%= notice %></p>
    <h1>一覧</h1>
      <%= link_to "つぶやく", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      <p>本文:<%= blog.content %></p>
      <%= link_to "編集する", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除する", blog_path(blog.id), method: :delete, data: { confirm: '削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

<%= link_to "つぶやく", new_blog_path %>

app/views/blogs/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>つぶやく</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kadai</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>